const { merge } = require('webpack-merge')
const common = require('./webpack.common')
const path = require('path')

module.exports = merge(common, {
    mode: 'development',
    output: {
        filename: 'bundle.js', // must match with the index.html
        path: path.resolve(__dirname, '../../../dist/client'), // folder name generated by webpack
        publicPath: '', // define the folder to the public path
        // clean: {
        //     dry: true,
        //     keep: /\.css/,
        // },
    },
    devtool: 'eval-source-map',
    devServer: {
        port: 3000,
        static: {
            directory: path.resolve(__dirname, '../../../dist/client'),
        },
        devMiddleware: {
            index: 'html/index.html',
            writeToDisk: true,
        },
        hot: true,
    },
    module: {
        rules: [
            {
                test: /\.s[ac]ss$/i,
                use: [
                    'style-loader',
                    'css-loader',
                    'postcss-loader',
                    'sass-loader',
                ],
            },
            {
                test: /\.css$/i,
                use: ['style-loader', 'css-loader', 'postcss-loader'],
            },
        ],
    },
})
